### ISSUE TITLE
write node error since upgrade to 1.0.4

### ISSUE THREAD

**Issue by thomkal** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#9]
Hi I'm facing write error from existing function (reading Homematic sensors and writing it to influxdb V.2.0.3)

Node function to prepare values:
`var pl = {
    bucket: 'homematic',
    precision: 's',
    data: [{
        measurement: msg.room ? msg.room.replace(/ /g, '\\ ') : 'undefined',
        tags: {
         'device': msg.device,
         'name': msg.deviceName.replace(/ /g, '\\ '),
         'deviceType': msg.deviceType
        },
        fields: {},
        timestamp: Math.round(msg.ts / 1000)
    }]
}
pl.data[0]['fields'][msg.datapoint] = msg.payload;
msg.payload = pl;
return msg;`

returns following json to the write node:
`Schlafzimmer Temperatur.TEMPERATURE : msg.payload : Object
object
bucket: "homematic"
precision: "s"
data: array[1]
0: object
measurement: "Schlafzimmer"
tags: object
device: "OEQ0128863"
name: "Schlafzimmer\ Temperatur"
deviceType: "HM-WDS40-TH-I-2"
fields: object
TEMPERATURE: 25.2
timestamp: 1611741808`

this gives now the following errors:

"Error: 400 on http://xxxx:xxxx/api/v2/query?org=xxx: {"code":"invalid","message":"compilation failed: error at @1:25-1:26: invalid statement: :"}"
And
Error: 400 on http://xxxx:xxxx/api/v2/query?org=xxx: {"code":"invalid","message":"error @1:1-1:11: undefined identifier Wohnzimmer"}

thanks in advance to correct that,
Best regards
Thomas

**Comment by thomkal** [comment]
Node red does not correct update the nodes, therefore it stays on a query node instead of a write node. changed this and now it works. Sorry 
Thoms
